{% set name = "awscli" %}
{% set version = "1.18.21" %}
{% set hash = "dc302ba80d3059bb6a68062708fcf7a8759e30537564b6236e2b09cdbab0d65b" %}

{% set vmajor,vminor,vpatch = version.split('.') %}
# ALWAYS DOUBLE-CHECK THESE OFFSETS AGAINST UPSTREAM setup.py
{% set botocore_major = vmajor | int + 0 %}
{% set botocore_minor = vminor | int - 3 %}
{% set botocore_patch = vpatch | int + 0 %}
{% set botocore_pin = botocore_major ~ '.' ~ botocore_minor ~ '.' ~ botocore_patch %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip

  run:
    - python
    - botocore =={{ botocore_pin }}
    - colorama >=0.2.5,<0.4.4
    - docutils >=0.10,<0.16
    - rsa >=3.1.2,<=3.5.0
    - s3transfer >=0.3.0,<0.4.0
    - pyyaml >=3.10,<5.4

test:
  imports:
    - awscli
    - awscli.customizations
    - awscli.customizations.cloudtrail
    - awscli.customizations.codedeploy
    - awscli.customizations.configservice
    - awscli.customizations.configure
    - awscli.customizations.datapipeline
    - awscli.customizations.ec2
    - awscli.customizations.emr
    - awscli.customizations.gamelift
    - awscli.customizations.s3
    - awscli.customizations.s3.syncstrategy

about:
  home: https://aws.amazon.com/cli/
  license_file: LICENSE.txt
  license: Apache 2.0
  license_family: Apache
  summary: Universal Command Line Environment for AWS.
  dev_url: https://github.com/aws/aws-cli
  doc_url: https://aws.amazon.com/cli/

extra:
  recipe-maintainers:
    - pmlandwehr
    - hajapy
    - tkelman
