{% set name = "awscli" %}
{% set version = "1.15.12" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "004db394c15e1b04c33d24a057a92736d147c3224b8772c484e00ceb2fe6ec77" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - botocore ==1.10.12
    - colorama >=0.2.5,<=0.3.7
    - docutils >=0.10
    - rsa >=3.1.2,<=3.5.0
    - s3transfer >=0.1.12,<0.2.0
    - pyyaml >=3.10,<=3.12

test:
  imports:
    - awscli
    - awscli.customizations
    - awscli.customizations.cloudtrail
    - awscli.customizations.codedeploy
    - awscli.customizations.configservice
    - awscli.customizations.configure
    - awscli.customizations.datapipeline
    - awscli.customizations.ec2
    - awscli.customizations.emr
    - awscli.customizations.gamelift
    - awscli.customizations.s3
    - awscli.customizations.s3.syncstrategy

about:
  home: https://aws.amazon.com/cli/
  license_file: LICENSE.txt
  license: Apache 2.0
  license_family: Apache
  summary: Universal Command Line Environment for AWS.
  dev_url: https://github.com/aws/aws-cli
  doc_url: https://aws.amazon.com/cli/

extra:
  recipe-maintainers:
    - pmlandwehr
    - hajapy
    - tkelman
