{% set name = "awscli" %}
{% set version = "1.25.46" %}
{% set hash = "14d84734b61054592e8dec7620ce3055bb0a1bc963d23f6ee24ffef1ff226fa6" %}

{% set vmajor,vminor,vpatch = version.split('.') %}
# ALWAYS DOUBLE-CHECK THESE OFFSETS AGAINST UPSTREAM setup.py
{% set botocore_major = vmajor | int + 0 %}
{% set botocore_minor = vminor | int + 2 %}
{% set botocore_patch = vpatch | int + 0 %}
{% set botocore_pin = botocore_major ~ '.' ~ botocore_minor ~ '.' ~ botocore_patch %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv  # [not unix]
  script: {{ PYTHON }} -m pip install . --no-deps -vv && mkdir -p $PREFIX/share/bash-completions/completions && echo complete -C aws_completer aws >$PREFIX/share/bash-completions/completions/aws  # [unix]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
#    - python >=3.7
    - pip

  run:
    - python
#    - python >=3.7
    - botocore =={{ botocore_pin }}
    - colorama >=0.2.5,<0.4.5
    - docutils >=0.10,<0.17
    - rsa >=3.1.2,<4.8
    - s3transfer >=0.6.0,<0.7.0
    - pyyaml >=3.10,<5.5

test:
  imports:
    - awscli
    - awscli.customizations
    - awscli.customizations.cloudtrail
    - awscli.customizations.codedeploy
    - awscli.customizations.configservice
    - awscli.customizations.configure
    - awscli.customizations.datapipeline
    - awscli.customizations.ec2
    - awscli.customizations.emr
    - awscli.customizations.gamelift
    - awscli.customizations.s3
    - awscli.customizations.s3.syncstrategy
  commands:
    - test -f $PREFIX/bin/aws_completer                   # [unix]
    - COMP_LINE="aws ec2 describe-inst" aws_completer     # [unix]

about:
  home: https://aws.amazon.com/cli/
  license_file: LICENSE.txt
  license: Apache-2.0
  license_family: Apache
  summary: Universal Command Line Environment for AWS.
  dev_url: https://github.com/aws/aws-cli
  doc_url: https://aws.amazon.com/cli/

extra:
  recipe-maintainers:
    - hajapy
    - tkelman
