{% set name = "awscli" %}
{% set version = "2.8.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

# v2 is not on PyPI https://github.com/aws/aws-cli/issues/6785
source:
  url: https://github.com/aws/aws-cli/archive/{{ version }}.tar.gz
  sha256: b37c64c6583153a420c7b80b34d62d33e317b40db561dfaeef027da083debb17

build:
  number: 0
  noarch: python
  # Build uses pep517 with a custom backend
  script: |
    {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  build:
    - python >=3.8                           # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python >=3.8
    - flit-core
    - pip

    # The build process generates the autocomplete index (scripts/gen-ac-index)
    # which requires importing awscli modules, so we need to install all runtime
    # dependencies too. YAML anchors don't support merging lists so we have to
    # duplicate everything :-(
    # Commented lines are the original requirements from
    # https://github.com/aws/aws-cli/blob/2.8.11/pyproject.toml#L30-L40
    # - colorama >=0.2.5,<0.4.4
    - colorama >=0.2.5,<0.5.0
    # - docutils >=0.10,<0.16
    - docutils >=0.10,<0.18
    - cryptography >=3.3.2,<=38.0.1
    - ruamel.yaml >=0.15.0,<=0.17.21
    - wcwidth <0.2.0
    - prompt_toolkit >=3.0.24,<3.0.29
    - distro >=1.5.0,<1.6.0
    - awscrt >=0.12.4,<=0.14.0
    - python-dateutil>=2.1,<3.0.0
    - jmespath>=0.7.1,<1.1.0
    - urllib3>=1.25.4,<1.27

  run:
    - python >=3.8
    # Commented lines are the original requirements from
    # https://github.com/aws/aws-cli/blob/2.8.11/pyproject.toml#L30-L40
    # They have been expanded to work with the available conda-forge packages on
    # more recent versions of Python
    # - colorama >=0.2.5,<0.4.4
    - colorama >=0.2.5,<0.5.0
    # - docutils >=0.10,<0.16
    - docutils >=0.10,<0.18
    - cryptography >=3.3.2,<=38.0.1
    - ruamel.yaml >=0.15.0,<=0.17.21
    - wcwidth <0.2.0
    - prompt_toolkit >=3.0.24,<3.0.29
    - distro >=1.5.0,<1.6.0
    - awscrt >=0.12.4,<=0.14.0
    - python-dateutil>=2.1,<3.0.0
    - jmespath>=0.7.1,<1.1.0
    - urllib3>=1.25.4,<1.27

test:
  commands:
    - aws --version
    - aws_completer
    # Check autocomplete index exists:
    - python -c 'import awscli, os; assert os.stat(os.path.join(os.path.dirname(awscli.__file__), "data", "ac.index")).st_size > 1e6'
    - COMP_LINE="aws ec2 describe-inst" aws_completer     # [unix]
  imports:
    # find $CONDA_PREFIX/lib/python3.9/site-packages/awscli/ -type f -name __init__.py | sed -re 's%.+(awscli.*)/__init__.py%- \1%' -re s'%/%.%g' | sort
    # Last updated version 2.8.11
    - awscli
    - awscli.autocomplete
    - awscli.autocomplete.local
    - awscli.autocomplete.serverside
    - awscli.autocomplete.serverside.custom_completers
    - awscli.autocomplete.serverside.custom_completers.ddb
    - awscli.autocomplete.serverside.custom_completers.logs
    - awscli.autoprompt
    - awscli.bcdoc
    - awscli.botocore
    - awscli.botocore.crt
    - awscli.botocore.docs
    - awscli.botocore.docs.bcdoc
    - awscli.botocore.retries
    - awscli.botocore.vendored
    - awscli.botocore.vendored.requests
    - awscli.botocore.vendored.requests.packages
    - awscli.botocore.vendored.requests.packages.urllib3
    - awscli.customizations
    - awscli.customizations.cloudformation
    - awscli.customizations.cloudtrail
    - awscli.customizations.codeartifact
    - awscli.customizations.codedeploy
    - awscli.customizations.configservice
    - awscli.customizations.configure
    - awscli.customizations.datapipeline
    - awscli.customizations.dlm
    - awscli.customizations.dynamodb
    - awscli.customizations.ec2
    - awscli.customizations.ecs
    - awscli.customizations.eks
    - awscli.customizations.emr
    - awscli.customizations.emrcontainers
    - awscli.customizations.gamelift
    - awscli.customizations.history
    - awscli.customizations.lightsail
    - awscli.customizations.logs
    - awscli.customizations.s3
    - awscli.customizations.s3.syncstrategy
    - awscli.customizations.servicecatalog
    - awscli.customizations.sso
    - awscli.customizations.wizard
    - awscli.customizations.wizard.ui
    - awscli.s3transfer

about:
  home: https://aws.amazon.com/cli/
  license_file: LICENSE.txt
  license: Apache-2.0
  license_family: Apache
  summary: Universal Command Line Environment for AWS.
  dev_url: https://github.com/aws/aws-cli
  doc_url: https://aws.amazon.com/cli/

extra:
  recipe-maintainers:
    - hajapy
    - tkelman
