# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.6

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "AZDW1uBIrtVBQIhQ5FTs+qRWCsSnTYQesZTPEzGf66Q8uSnK4Rs0G4p1i0onBeKejlgqK7oyx4ATPEMX9dlHI+QIFYHWhxELp1NdDYKKF15A+loKQTbUnLcq+syaK8ZHBgaSJ4T5jHf0MYlCujzOJZEfy4rnnsBSi3K+mu6NavOwhKLcJcbq51sfM0Z3dGgOv+9YYaCaksrq6U1AuzxhlXh7vZMllZaRDGKW1ib0zHSJz7fLy57UmbfzznKtSVDvQJx77KSxkBYP2b0uuLLbjo6/JM89fG9kvRzy8LnEWg4M26rVtWJLF1+Ykgap/yXy5UidoatsTflQLsG7b31aUpRqJ7BnjNAUsj34AINsMKNRybSDjh81xI2XcMBBtGNNf1rGdFPU80GCknKDqeH8kLAWJQOQ7dc+Ui3KOkGl0KAOPyQZHWQbOfOhEEibX1RvC1qVRO1hLnAKjLaRDyFtzhxFoK5pWCdFR5JDcLR8puYZLo5rxhj/NZi8y+vfuJttFKQUQ9C+CF/rj2bIiTNEGo+yetoFluV12wUIJdBEpwhHbrSD60VBDratacpD8znf5BiufyqIzJZwnl9E39yMXz/dlNeXCf3zRpViC43P9Cru45ypWG572ZmtdMzmQOnmDnjTGy4TH/2ewG6f2yCdo13sJOdONyAiCzFXnA5zKUw="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
